version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "xxxxxxxxxxxxxxxxxxxxxxxxxxx" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/Room/deploy-me.sh"
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
