version: 2
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0d:26:ad:57:1a:4b:6d:b4:e6:c5:24:a9:0e:73:2e:7a" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/Room/deploy-me.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
